base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginPage, name='login'),
    path('logout/', views.LogoutUser, name='logout'),
    path('', views.home, name='home'),
    path('room/<str:pk>/', views.room, name='room'),
    path('create-room/', views.CreateRoom, name='create-room'),

    path('update-room/<str:pk>/', views.UpdateRoom, name='update-room'),
    path('delete-room/<str:pk>/', views.DeleteRoom, name='delete-room'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse


urlpatterns = [
    path('admin/', admin.site.urls), # Admin site URL
    path('', include('base.urls')), # Include URLs from the base app
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # participants = 
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created'] # Order by updated first, then created

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]  # Return the first 50 characters of the message body
    

base/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):

    class Meta:
        model = Room
        fields = '__all__'

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import Room, Topic
from .forms import RoomForm

# Create your views here.

# rooms = [
#     {'id': 1, 'name': 'Room 1 - learn python'},
#     {'id': 2, 'name': 'Room 2 - Design with me'},
#     {'id': 3, 'name': 'Room 3 - Frontend developers'}
# ]


def LoginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

    try:
        user = User.objects.get(username=username)
    except:
        messages.error(request, 'User does not exist')
    
    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return redirect('home')
    else:
        messages.error(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'base/login_register.html', context)

def LogoutUser(request):
    logout(request)
    return redirect('home')

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) | 
        Q(description__icontains=q)
    )
    topics = Topic.objects.all()
    rooms_count = rooms.count()
    context = {'rooms': rooms, 'topics': topics, 'rooms_count': rooms_count}
    return render(request, 'base/home.html', context)

def room(request, pk):
    room = Room.objects.get(id=pk)
    context = {'room': room}
    return render(request, 'base/room.html', context)

def CreateRoom(request):
    form = RoomForm()

    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form}
    return render(request, 'base/room_form.html', context)

def UpdateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('home')
        
    context = {'form': form}
    return render(request, 'base/room_form.html', context)

def DeleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    
    context = {'object': room}
    return render(request, 'base/delete.html', context)

base/templates/base/delete.html
{% extends 'main.html' %}




{% block content %}
   <h1>Delete Room</h1>
   <p>Are you sure you want to delete this room? {{ obj }}</p>
   <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
   <form method="POST">
       {% csrf_token %}
       <input type="submit" value="Confirm" />
   </form>
   <a href="{% url 'home' %}">Cancel</a>
{% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}

<style>
    .home-container {
        display: grid;
        grid-template-columns: 1fr 3fr;
    }
</style>

    <h1>Home Page</h1>

<div class="home-container">

    {% comment %} <div>
        <a href="{% url 'home' %}">Home</a>
    </div> {% endcomment %}

    <div>
        <h3>Browse Topics:</h3>
        <hr>
        {% for topic in topics %}
            <div>
                <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }}</a>
                <span>({{ topic.room_set.count }})</span>
            </div>
        {% endfor %}
    </div>

    <div>
    <a> Create a new room</a>
    <h5>{{room_count}} set available rooms</h5>
    <hr>
    <a href="{% url 'create-room' %}">Create a new room</a>
    <hr>

    <div>
    {% for room in rooms %}
        <div>
            <span>@{{ room.host.username }}</span>
            <h5>{{room.id}} -- <a href="{% url 'room' room.id %}">{{ room.name }}</a></h5>
            <small>{{room.topic.name}}</small>
            <a href="{% url 'update-room' room.id %}">Edit</a>
            <a href="{% url 'delete-room' room.id %}">Delete</a>
            <hr>
        </div>
    {% endfor %}



{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        
        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter your username" required />

        <label>Password:</label>
        <input type="password" name="password" placeholder="Enter your password" required />

        <input type="submit" value="Login" placeholder="Login" />
    </form>
</div>
{% endblock %}

base/templates/base/room.html
{% extends 'main.html' %}

{% block content %}
<h1>{{ room.name }}</h1>
   <h1>Room Page</h1>
   <p>This is a study room!</p>
{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content %}
   <h1>Create a New Room</h1>
   <form method="POST" action="">
       {% csrf_token %}
       {{ form.as_p}}

       <input type="submit" value = "Submit" />

   </form>

{% endblock %}

templates/home.html
{% extends 'main.html' %}

{% block content %}
   <h1>Home Page</h1>
   <p>Welcome to StudyBud!</p>

   <div>

    <div>
        {% for room in rooms %}
            <div>
                <h5>{{room.id}} -- {{ room.name }}</h5>
        {% endfor %}
    </div>
    </div>


{% endblock %}

templates/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>StudyBud</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% comment %} <link rel='stylesheet' type='text/css' media='screen' href='main.css'> {% endcomment %}
</head>

<body>
    {% include 'navbar.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
        <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        
    {% block content %}
   <h1>Home Page</h1>
   <p>Welcome to StudyBud!</p>
    {% endblock %}
</body>
</html>

templates/navbar.html
<a href="/">
    <h1> Logo </h1>
</a>

<form method="GET" action="{% url 'home' %}">
    <input type="text" name="q" placeholder="Search rooms..." value="{{ request.GET.q }}">
    <button type="submit">Search</button>


{% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
{% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}

<a href="{% url 'login' %}">Login</a>

<hr>

templates/room.html
{% extends 'main.html' %}

{% block content %}
   <h1>Room Page</h1>
   <p>This is a study room!</p>
{% endblock %}